### ISSUE TITLE
Translation en anglais 

### ISSUE THREAD

**Issue by Beatrix-droid** [CESI-EAT/cesieat-client#31]
Je voudrais crée le translation en anglais des les README documents.

(I would love to contribute to this project my creating a translation of the README docs and the contribution guidelines.
Let me know if this could help!)

**Comment by milinkovitch** [comment]
Hi there ! 

You are totally free if you want to translate our README.

Please create your own branch et make a pull request once it's done !

Thank you for your help !

**Comment by Beatrix-droid** [comment]
Thank you!
I will work on this after work, and am planning to make a PR by Friday at the latest😊
